---
sudo: false
language: rust
rust:
  - nightly
  - 1.0.0

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | RUST_TEST_THREADS=1 bash
  - cargo doc --no-deps

addons:
  apt:
    packages:
      - gcc-multilib

# Deploy documentation to S3 for specific branches. At some
# point, it would be nice to also support building docs for
# a specific tag
# deploy:
#   provider: s3
#   access_key_id: AKIAIGFX36YKEFRZJAXA
#   secret_access_key:
#     secure: Q10KEdtBoYxaGXtt23L00J0obv9fpVWtao8YKFEroZMOmvu8Sq2+9aTNGEQRp2OojOxuu+DjZInJlUDFhq6trmV3kpZH2BF7cNRxiZQpQ2FEmlr6ZpYN38GhcIUKdxXqVwXiASJi6j+vz6QdpaOGCs5lQC3VhM5sn49MFXNUrFU=
#   bucket: rustdoc
#   endpoint: "rustdoc.s3-website-us-east-1.amazonaws.com"
#   skip_cleanup: true
#   local-dir: target/doc
#   upload-dir: nix/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}
#   acl: public_read
#   on:
#     condition: "\"$TRAVIS_RUST_VERSION/$ARCH\" == \"1.0.0/x86_64\""
#     repo: carllerche/nix-rust
#     branch:
#       - master
